version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT:-8080}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgadmin_data: